[project]
name = "pytchat"
version = "0.1.0"
description = "Python Terminal Chat Using Apache Kafka"
authors = [
    {name = "dMario24", email = "data.mario24@gmail.com"},
]
dependencies = [
    "textual>=0.77.0",
    "textual-dev>=1.5.1",
]
requires-python = ">=3.8"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false

[tool.pdm.dev-dependencies]
test = [
    "pytest>=8.3.2",
    "pytest-cov>=5.0.0",
]

[tool.pytest.ini_options]
pythonpath = "src"

[project.urls]
Homepage = "https://github.com/dMario24/pytchat"
Issues = "https://github.com/dMario24/pytchat/issues"

[project.scripts]
pytchat-ping = 'pytchat.cli:ping'